kiwicom/stopovers

components/shared/Button.js
stories/Button.stories.js

A general button to be used across the landing page

Add general button

---

components/hero/Action.js
components/hero/Content.js
components/hero/Hero.js
components/hero/SearchAction.js
components/shared/ActionText.js
components/shared/Text.js
package.json
pages/_document.js
pages/index.js
stories/Button.stories.js
yarn.lock

closes https://github.com/kiwicom/stopovers/issues/5

Header section

---

components/hero/Content.js
components/hero/Hero.js
components/shared/Button.js
components/shared/Description.js
components/sliderSection/SliderSection.js
pages/_document.js

Added just necessary amount of responsiveness
Will be polished in https://github.com/kiwicom/stopovers/issues/23

Make header section more responsive 

---

components/video/Video.js
package.json
pages/index.js
yarn.lock

Add video section

---

.eslintrc
components/search/Search.js
pages/index.js

Add search section

---

components/itinerary/Itinerary.js

Add a button to itinerary

---

components/footer/Footer.js
pages/index.js

Make tablet layout for footer

---

components/itinerary/ItemContent.js
components/itinerary/Itinerary.js
components/itinerary/ItineraryItem.js
components/shared/SectionTitle.js
pages/index.js

Make itinerary responsive

---

components/articles/ArticleItem.js
components/articles/Articles.js
components/footer/Footer.js
pages/index.js

Make articles scrollable on tablet

---

.eslintrc
components/itinerary/Itinerary.js
components/itinerary/mockedData.js
components/shared/Dropdown.js
components/shared/DropdownMobile.js
package.json
stories/Dropdown.stories.js
yarn.lock

Customize dropdown

---

components/articles/Articles.js
components/hero/Action.js
components/itinerary/ItemContent.js
components/itinerary/Itinerary.js
components/itinerary/ItineraryItem.js

Add pulse to hero button

---

components/banner/Banner.js
pages/index.js

Hide and show banner on scroll

---

etc/marketingHelpers.js
pages/index.js

Store marketing params to localStorage

---

components/menu/Menu.js
etc/helpers.js
pages/index.js

 Prevent router from clearing current url params

---

components/search/Search.js
pages/index.js

 Apply from, to and lang to widget on client side

---

components/search/Search.js

should be merged after #135 
closes #132

Add userid to widget and remove cookies banner

---

components/itinerary/ItemContent.js
components/itinerary/Itinerary.js
components/itinerary/ItineraryContext.js
components/itinerary/ItineraryItem.js
static/locales/en-GB.json

Add show more to itinerary on mobile

---

next.config.js

Add fallbacks to spanish

---

pages/_document.js

Add global styles for react select

---

next.config.js

Improve language fallbacks

---

components/search/Search.js
etc/helpers.js

Support passengers, departure and return widget params

---

package.json
stories/Video.stories.js
stories/__snapshots__/Storyshots.test.js.snap
yarn.lock

Add Video story and fixes

---

components/menu/Menu.js

Update Holidays url

---

.babelrc
.storybook/.babelrc
package.json
stories/Itinerary.stories.js
stories/__snapshots__/Storyshots.test.js.snap
yarn.lock

Add itinerary to storybook

---

components/articles/ArticleItem.js
components/articles/Articles.js

Rewrite Articles to use flexbox

---

components/banner/Banner.js
stories/Banner.stories.js

Convert Banner to flexbox

---

components/itinerary/Itinerary.js

Convert Itineraries to flexbox

---

components/partners/Partners.js

Convert Partners to flexbox

---

components/hero/Action.js
components/hero/Content.js
components/hero/Hero.js

Convert Hero to flexbox

---

components/menu/Menu.js
etc/helpers.js
next.config.js
pages/index.js

Add flags for sg ca us

---

components/footer/Footer.js

Convert Footer to flexbox

---

components/sliderSection/Slider.js
components/sliderSection/SliderSection.js

Convert SliderSection to flexbox

---

components/search/Search.js

Convert Search to flexbox

---

static/locales/menuItems_en-GB.json

Add transalation file for header and footer

---

components/articles/ArticleItem.js
components/hero/Hero.js
components/itinerary/ItineraryItem.js
components/sliderSection/Slider.js

Adjust image sizes

---

components/footer/Footer.js

Footer was broken on 1440px wide browsers.

Fix footer alignment

---

components/articles/Articles.js
components/banner/Banner.js
components/footer/Footer.js
components/hero/Action.js
components/hero/Content.js
components/itinerary/ItemContent.js
components/itinerary/Itinerary.js
components/menu/Menu.js
components/shared/Dropdown.js
components/shared/SectionTitle.js
components/shared/StyledText.js
components/sliderSection/SliderSection.js
components/stickyAction/SearchAction.js
package.json
pages/index.js
yarn.lock

Upgrade Nitrolib

---

etc/__tests__/__snapshots__/helpers.test.js.snap
etc/__tests__/helpers.test.js
etc/helpers.js
next.config.js
pages/index.js

I also did some refactoring of `pages/index.js` and related files.
Closes #215

Add SG,CA flags

---

components/shared/MetaHead.js
pages/index.js

Use context in MetaHead for translations
